################################################################
# Discord-API properties
################################################################
discord:
    password: al3DsplDSIn47GZg7FKK
    username: j_ulianpeters@gmx.de

################################################################
# Spring-Data properties
################################################################
# Always force db migration
spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect

################################################################
# Teamup
################################################################
teamup:
    apiKey: bf3bb3cfc9a84f988e5c1a14cbb369a615b8ad78ea98232f5051a1b5fb5ec816
    calendarId: ks5f1fd3feec094935
#spring.jpa.hibernate.ddl-auto = update
#spring.datasource.url = jdbc:derby:database.db
#derby.system.homeSystem.setProp = .
#spring.datasource.driverClassName=org.apache.derby.jdbc.EmbeddedDriver
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.DerbyDialect
#spring.jpa.show-sql=false
#https://discord.gg/0wBPufmfdqbmn224


# FLYWAY (FlywayProperties)
#flyway.enabled=true
#flyway.locations=classpath:db/migration